=== SDGforskning/sdg-tagger/tests/json_schema/sdg_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "number": {
      "type": "integer"
    },
    "generated_datetime": {
      "type": "string"
    },
    "pre-search": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/phrase"
      }
    },
    "goals": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/goal"
      }
    },
    "mentions": {
      "type": "object",
      "properties": {
        "logic_rule": {
          "type": "string",
          "format": "logic-rule-pattern"
        },
        "_comment": {
          "type": "string"
        },
        "termlists": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/termlist"
          }
        }
      },
      "required": [
        "logic_rule",
        "termlists"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "name",
    "number",
    "generated_datetime",
    "goals",
    "mentions"
  ],
  "additionalProperties": false,
  "definitions":{
    "termlist": {
        "type": "object",
        "properties": {
          "termlist_name": {
            "type": "string"
          },
          "formatting_rule": {
              "type": "string"
          },
          "na": {
              "type": "boolean"
          },
          "case": {
              "type": "boolean"
          },
          "_comment": {
            "type": "string"
          },
          "wordlist_en": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "wordlist_no": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          }
        },
        "required": [
            "termlist_name",
            "formatting_rule",
            "na",
            "case",
            "wordlist_en",
            "wordlist_no"
        ],
      "additionalProperties": false
    },
    "phrase": {
      "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "number": {
              "type": "integer"
            },
            "_comment": {
              "type": "string"
            },
            "logic_rule": {
              "type": "string",
              "format": "logic-rule-pattern"
            },
            "sentence_split": {
              "type": "boolean"
            },
            "termlists": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/termlist"
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "logic_rule",
            "sentence_split",
            "termlists"
          ]
        },
    "goal": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "phrases": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/phrase"
              }
            }
          },
          "required": [
            "name",
            "phrases"
          ],
          "additionalProperties": false
        }
  }
}

=== SDGforskning/sdg-tagger/src/phrases/sdg1.json
{
    "name":"sdg1",
    "number": 1,
    "generated_datetime":"2025-09-13 09:49:07",
    "pre-search":[],
    "goals":[
        {
            "name":"1",
            "phrases":[
                {
                    "number": 1,
                    "logic_rule": "([termlist1_1])",
                    "sentence_split": true,
                    "termlists": [
                        {
                            "termlist_name": "termlist1_1", 
                            "formatting_rule": "default", 
                            "na": false,
                            "case": false,
                            "wordlist_en": [
                                "extreme poverty", "severe poverty", "deep poverty", "abject poverty", "absolute poverty", "destitution", "global poverty", "international poverty"
                            ],
                            "wordlist_no": [
                                "ekstrem fattigdom", "global fattigdom", "internasjonal fattigdom"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name":"b",
            "phrases":[
                {
                    "number": 1,
                    "logic_rule": "([termlist1_ba] | [termlist1_ba_trunc]) & [termlist1_bb] | ([termlist1_bc] & ([termlist1_bd] | [termlist1_bd_trunc]))",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "termlist1_ba", 
                            "formatting_rule": "default", 
                            "na": false,
                            "case": false,
                            "wordlist_en": [
                                "legislat", "program", "strateg", "policy", "policies", "planning", "framework", "initiativ"
                            ],
                            "wordlist_no": [
                                "lovverk", "lovgiv", "politikk", "retningslinje", "utredning", "utgreiing", "rammeverk", "tiltaksplan", "planer", "planar"
                            ]
                        },
                        {
                            "termlist_name": "termlist1_ba_trunc",
                            "formatting_rule": "specific", 
                            "na": false,
                            "case": false,
                            "wordlist_en": ["law", "laws", "plan", "plans"],
                            "wordlist_no": []
                        },
                        {
                            "termlist_name": "termlist1_bb",
                            "formatting_rule": "default", 
                            "na": false,
                            "case": false,
                            "wordlist_en": ["anti poverty", "anti-poverty", "antipoverty"],
                            "wordlist_no": []
                        },
                        {
                            "termlist_name": "termlist1_bc",
                            "formatting_rule": "default", 
                            "na": false,
                            "case": false,
                            "wordlist_en": ["poverty"],
                            "wordlist_no": ["fattig"]
                        },
                        {
                            "termlist_name": "termlist1_bd",
                            "formatting_rule": "default", 
                            "na": false,
                            "case": false,
                            "wordlist_en": ["minimi", "reduc", "mitigat", "alleviat", "tackl", "fight", "combat", "ending", "eliminat", "eradicat", "prevent", "out of", "overcom", "escap", "relief"],
                            "wordlist_no": ["reduser", "bekjemp", "forhind", "nedkjemp", "motarbeid", "forebygg", "førebygg", "førebu", "utrydd", "kvitt", "løft", "ut av " ]
                        },
                        {
                            "termlist_name": "termlist1_bd_trunc",
                            "formatting_rule": "specific", 
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": ["mot", "imot", "kamp", "kampen"]
                        }
                    ]
                }
            ]
        }
    ],
    "mentions": {
        "logic_rule": "([termlist_sdg_a] | [termlist_sdg_f] | ([termlist_sdg_b] & [termlist_sdg_c]) | ([termlist_sdg_d] & [termlist_sdg_e]))",
        "termlists" :[
            {
                "termlist_name": "termlist_sdg_a",
                "formatting_rule": "specific", 
                "na": false,
                "case": false,
                "wordlist_en": ["SDG 1", "SDGs 1", "SDG1", "sustainable development goal 1"],
                "wordlist_no": ["SDG 1", "SDG1","bærekraftsmål 1", "berekraftsmål 1"]
            },
            {
                "termlist_name": "termlist_sdg_b",
                "formatting_rule": "default", 
                "na": false,
                "case": false,
                "wordlist_en": ["sustainable development goal"],
                "wordlist_no": ["bærekraftsmål", "berekraftsmål"]
            },
            {
                "termlist_name": "termlist_sdg_c",
                "formatting_rule": "specific", 
                "na": false,
                "case": false,
                "wordlist_en": ["goal 1"],
                "wordlist_no": ["mål 1"]
            },
            {
                "termlist_name": "termlist_sdg_d",
                "formatting_rule": "specific", 
                "na": false,
                "case": false,
                "wordlist_en": ["sustainable development goal.*", "SDG", "goal 1"],
                "wordlist_no": ["SDG", "bærekraftsmål", "berekraftsmål", "mål 1"]
            },
            {
                "termlist_name": "termlist_sdg_e",
                "formatting_rule": "default", 
                "na": false,
                "case": false,
                "wordlist_en": ["poverty"],
                "wordlist_no": ["fattig"]
            },
            {
                "termlist_name": "termlist_sdg_f",
                "formatting_rule": "default", 
                "na": false,
                "case": false,
                "wordlist_en": ["no poverty"],
                "wordlist_no": ["utrydde fattigdom"]
            }
        ]
    }
}

=== SDGforskning/sdg-tagger/src/phrases/sdg13_template.json
{
    "name": "sdg13",
    "number": 13,
    "generated_datetime": "09-12-2025 10:07:35",
    "pre-search": [],
    "goals": [
        {
            "name": "1",
            "phrases": [
                {
                    "number": 1,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                }
            ]
        },
        {
            "name": "2",
            "phrases": [
                {
                    "number": 1,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                },
                {
                    "number": 2,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                },
                {
                    "number": 3,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                }
            ]
        },
        {
            "name": "3",
            "phrases": [
                {
                    "number": 1,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                }
            ]
        },
        {
            "name": "a",
            "phrases": [
                {
                    "number": 1,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                },
                {
                    "number": 2,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                },
                {
                    "number": 3,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                }
            ]
        },
        {
            "name": "b",
            "phrases": [
                {
                    "number": 1,
                    "logic_rule": "()",
                    "sentence_split": false,
                    "termlists": [
                        {
                            "termlist_name": "",
                            "formatting_rule": "",
                            "na": false,
                            "case": false,
                            "wordlist_en": [],
                            "wordlist_no": []
                        }
                    ]
                }
            ]
        }
    ],
    "mentions": {
        "logic_rule": "()",
        "termlists": [
            {
                "termlist_name": "",
                "formatting_rule": "",
                "na": false,
                "case": false,
                "wordlist_en": [],
                "wordlist_no": []
            },
            {
                "termlist_name": "",
                "formatting_rule": "",
                "na": false,
                "case": false,
                "wordlist_en": [],
                "wordlist_no": []
            }
        ]
    }
}
